export interface TestType {
  id: string;
  link: string | null;
  test_name: string;
  test_number: number;
  test_type: string;
  ordered: boolean;
  taken: boolean;
}

export const testsList: TestType[] = [
	{
		id: "DHEA",
		test_name: "DHEA Sulfate, Immunoassay",
		test_type: "SERUM",
		test_number: 402,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "CBCB",
		test_name: "CBC (H/H, RBC, Indices, WBC, Plt)",
		test_type: "BLOOD",
		test_number: 1759,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "ESTR",
		test_name: "Estradiol",
		test_type: "SERUM",
		test_number: 4021,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "PSAT",
		test_name: "PSA, Total",
		test_type: "SERUM",
		test_number: 5363,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "HSRP",
		test_name: "hs-CRP",
		test_type: "SERUM",
		test_number: 10124,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "CMTP",
		test_name: "Comprehensive Metabolic Panel",
		test_type: "SERUM",
		test_number: 10231,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "LPDL",
		test_name: "Lipid Panel with Reflex to Direct LDL",
		test_type: "SERUM",
		test_number: 14852,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "TFBT",
		test_name: "Testosterone, Free, Bioavailable and Total, MS",
		test_type: "SERUM",
		test_number: 14966,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "HA1C",
		test_name: "Hemoglobin A1c with eAG with Reflex to GlycoMark(R)",
		test_type: "BLOOD",
		test_number: 16320,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "VD1D",
		test_name: "Vitamin D, 1,25-Dihydroxy",
		test_type: "SERUM",
		test_number: 16558,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "SHBG",
		test_name: "Sex Hormone Binding Globulin (SHBG)",
		test_type: "SERUM",
		test_number: 30740,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "TSFT",
		test_name: "TSH with Reflex to Free T4",
		test_type: "SERUM",
		test_number: 36127,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "FERT",
		test_name: "Ferritin",
		test_type: "SERUM",
		test_number: 457,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "FOLS",
		test_name: "Folate, Serum",
		test_type: "SERUM",
		test_number: 466,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "LDHD",
		test_name: "Lactate Dehydrogenase (LD)",
		test_type: "SERUM",
		test_number: 593,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "PROG",
		test_name: "Progesterone, Immunoassay",
		test_type: "SERUM",
		test_number: 745,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "SEDW",
		test_name: "Sed Rate by Modified Westergren",
		test_type: "BLOOD",
		test_number: 809,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "URCA",
		test_name: "Uric Acid",
		test_type: "SERUM",
		test_number: 905,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "VITB",
		test_name: "Vitamin B12 (Cobalamin)",
		test_type: "SERUM",
		test_number: 927,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "VITE",
		test_name: "Vitamin E (Tocopherol)",
		test_type: "SERUM",
		test_number: 931,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "ZINC",
		test_name: "Zinc",
		test_type: "PLASMA-UNSPECIFIED VIAL POUR",
		test_number: 945,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "URCM",
		test_name: "Urinalysis, Complete",
		test_type: "RANDOM",
		test_number: 5463,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "ITTC",
		test_name: "Iron, Total and Total Iron Binding Capacity",
		test_type: "SERUM",
		test_number: 7573,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "ABRT",
		test_name: "ABO Group and Rh Type",
		test_type: "BLOOD",
		test_number: 7788,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "VD25",
		test_name: "Vitamin D, 25-Hydroxy, Total, Immunoassay",
		test_type: "SERUM",
		test_number: 17306,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "HOMO",
		test_name: "Homocysteine",
		test_type: "SERUM",
		test_number: 31789,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "T3FR",
		test_name: "T3, Free",
		test_type: "SERUM",
		test_number: 34429,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "VTB6",
		test_name: "Vitamin B6, Plasma",
		test_type: "PLASMA-UNSPECIFIED VIAL POUR",
		test_number: 926,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "VITC",
		test_name: "Vitamin C",
		test_type: "SERUM",
		test_number: 929,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "VTB1",
		test_name: "Vitamin B1 (Thiamine), Blood, LC/MS/MS",
		test_type: "BLOOD",
		test_number: 5042,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "FSHL",
		test_name: "FSH and LH",
		test_type: "SERUM",
		test_number: 7137,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "T3RV",
		test_name: "T3 Reverse, LC/MS/MS",
		test_type: "SERUM",
		test_number: 90963,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "OMGC",
		test_name: "OmegaCheck(R)",
		test_type: "BLOOD",
		test_number: 92701,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "ALPI",
		test_name: "Advanced Lipid Panel with Inflammation, Cardio IQ(R)",
		test_type: "SERUM",
		test_number: 94220,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "FIAC",
		test_name: "Fibrinogen Activity, Clauss",
		test_type: "VARIED",
		test_number: 461,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "INSU",
		test_name: "Insulin",
		test_type: "SERUM",
		test_number: 561,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "MGRB",
		test_name: "Magnesium, RBC",
		test_type: "OTHER",
		test_number: 623,
		link: null,
		ordered: false,
		taken: false,
	},
	{
		id: "T4FR",
		test_name: "T4 Free (FT4)",
		test_type: "SERUM",
		test_number: 866,
		link: null,
		ordered: false,
		taken: false,
	},
];
